#! /bin/sh

# shortcuts
alias :q='exit'
alias :q!='exit'
alias :wq='exit'
alias clone='alacritty --working-directory "$PWD" &'

alias vi='nvim'
alias vim='nvim'
for nvimcmd in "vi" "vim" "nvim"; do
    alias ${nvimcmd}.='nvim .'
    alias ${nvimcmd}:='nvim ..'
    alias ${nvimcmd}..='nvim ..'
    alias ${nvimcmd}::='nvim ../..'
    alias ${nvimcmd}conf='nvim ~/.config/'
    alias ${nvimcmd}config='nvim ~/.config/'
done

alias cd:='cd ..'
alias cd::='cd ../..'
alias cd:::='cd ../../..'
alias cdconf='cd ~/.config'
alias cdp='cd ~/Projects/'
alias cd..='cd ..'
alias cd~='cd ~'
alias cd-='cd -'

alias eza='eza --color=always --classify --git --icons'
alias ls='eza --git-ignore'
alias la='eza --all'
alias ll='eza --long --header'
alias lla='eza --all --long --header'
alias tree='eza --tree --git-ignore'
alias trea='eza --tree --all'
alias cat='bat'
alias grep='rg'

alias shtdwn='shutdown -h now'
alias sshtdwn='sudo shutdown -h now'
alias sreboot='sudo reboot'
alias suspend='systemctl suspend'
alias ssuspend='sudo systemctl suspend'

alias parusyu='paru -Syu'
alias rmorphans='sudo pacman -Rns $(pacman -Qtdq)'
alias listinstalled='pacman -Qe'
alias clearcache='paru -Sc ; paccache -r'

alias screen='scrot -d 5 -c'
alias screen10='scrot -d 10 -c'
alias screen15='scrot -d 15 -c'
alias notimeout='xset -dpms && xset s off'

alias hdmileftdp='xrandr --auto --output HDMI-1 --mode 1920x1080 --left-of DP-1'
alias hdmirightdp='xrandr --auto --output 1920x1080 --right-of DP'
alias hdmioff='xrandr --output HDMI-1 --off'
alias dplefthdmi='xrandr --auto --output DP-1 --mode 1920x1080 --left-of HDMI-1'
alias dprighthdmi='xrandr --auto --output DP-1 --mode 1920x1080 --right-of HDMI-1'
alias rotdpright='xrandr --output DP-1 --rotate right'
alias rotdpleft='xrandr --output DP-1 --rotate left'
alias rotdpnorm='xrandr --output DP-1 --rotate normal'
alias dpoff='xrandr --output DP-1 --off'

alias searchssh='sudo nmap -p 22'
alias searchopenssh='sudo nmap --open -p 22'

alias editproject='nvim-subdir /home/elucan/Projects'
alias editconfig='nvim-subdir /home/elucan/.config'
